# Generated by Django 5.1.6 on 2026-05-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_anonymous_alter_feedback_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='target',
            field=models.CharField(choices=[('department', 'Department'), ('student_affairs', 'Student Affairs'), ('admin', 'Admin')], max_length=50),
        ),
    ]
